[tools]
bat = "0.25.0"
chezmoi = "2.61.0"
cue = "0.9.1"
difftastic = "0.58.0"
eksctl = "0.180.0"
fd = "10.1.0"
fzf = "0.52.1"
go = "1.25.0"
goreleaser = "2.4.6"
jj = "latest"
just = "1.28.0"
krew = "0.4.4"
kubectl = "1.30.1"
lua = "5.1.5"
neovim = "0.11.5"
node = "22.2.0"
pkl = "0.29.1"
protoc = "latest"
python = "3.14"
ripgrep = "14.1.0"
ruby = "3.3.0"
rust = "stable"
starship = "1.19.0"
terraform = ["1.3", "1.8.4", "1.5.5"]
terragrunt = ["0.58.12", "0.68.3"]
terramate = "0.14.5"
usage = "0.3.0"
xh = "0.23.1"
zellij = "0.41.1"
zig = ["0.13.0", "0.14.0"]
zoxide = "latest"
