[tools]
bat = "0.26.1"
chezmoi = "2.69.3"
cue = "0.9.1"
difftastic = "0.67.0"
eksctl = "0.221.0"
fd = "10.1.0"
fzf = "0.52.1"
go = "1.25.6"
goreleaser = "2.13.3"
jj = "0.37.0"
just = "1.46.0"
krew = "0.4.5"
kubectl = "1.35.0"
lua = "5.1.5"
neovim = "0.11.5"
node = "25.4.0"
pkl = "0.30.2"
protoc = "33.4"
python = "3.14.2"
ripgrep = "15.1.0"
ruby = "4.0.1"
rust = "1"
starship = "1.24.2"
terraform = "1.14.3"
terragrunt = "0.98.0"
terramate = "0.15.5"
usage = "2.13.1"
xh = "0.25.3"
zellij = "0.43.1"
zig = "0.14.0"
zoxide = "0.9.8"
